baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TTC Teneramonda'

enableRobotsTXT = true

############################## Menu #############################

[menu]
  [[menu.main]]
  name = "Over ons"
  URL = "/over"
  weight = 1

  [[menu.main]]
  name = "Sponsers"
  URL = "/sponsers"
  weight = 2

  [[menu.main]]
  name = "Kalender"
  URL = "/kalender"
  weight = 3

  [[menu.main]]
  name = "Kledij"
  URL = "/kledij"
  weight = 4

  [[menu.main]]
  name = "Leden"
  URL = "/leden"
  weight = 5

  [[menu.main]]
  name = "Contact"
  URL = "/contact"
  weight = 6


[outputs]
    home = ["html", "json"]
    section = ["HTML", "JSON"]

[module]
    [module.hugoVersion]
        min = "0.128.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true
[build.buildStats]
    enable = true
[[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
[[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[markup]
    [markup.highlight]
        style = 'github'
